/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;


import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        String path="./app/src/main/resources/gates.js";
        ArrayList<String> acceptedArr =errors(path);
        for (String item:
             acceptedArr) {
            System.out.println(item);
        }
    }
    public static ArrayList<String> errors(String path){
        ArrayList<String> errorsArr=new ArrayList<String>();
        try {
            Path acceptedPath = Paths.get(path);
            List<String> fileLines = Files.readAllLines(acceptedPath);
            int lineNum=0;
            for (String line : fileLines) {
                lineNum++;
                if (line.endsWith("}") || line.endsWith("{") || line.equals("") || line.endsWith(
                        ";") || line.contains("if") || line.contains("else")) {
                } else {
                    errorsArr.add("Line "+lineNum+": Missing semicolon.");
                }
            }
        } catch (IOException exception) {
            System.out.println("An error occurred while reading from file");
        }
        return errorsArr;
    }


}
