/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.checkerframework.checker.units.qual.A;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    void testInstanceOfRestaurant() {
        System.out.println("test 1 SUCCESS");
        Restaurant McDonald = new Restaurant();
        McDonald.setName("McDonald"); // the name of the resturant
        McDonald.setStars(0); //default stars start from zero
        McDonald.setPrice(2);
        String expected = "Restaurant{name='McDonald', stars=0.0, price='$$', reviews=[]}";
        assertEquals(expected, McDonald.toString());
    }

    @Test
    void testInstanceOfReview() {
        System.out.println("test 2 SUCCESS");
        Review review = new Review();
        review.setAuthor("khalid");
        review.setBody("bad service");
        review.setNumOfStars("1");
        String expected = "Review{body='bad service', author='khalid', numOfStars=1}";
        assertEquals(expected, review.toString());
    }

    @Test
    void testReviewForOneRestaurant() {
        System.out.println("test 3 SUCCESS");
        Restaurant kfc = new Restaurant();
        kfc.setName("kfc");
        kfc.setStars(0);
        kfc.setPrice(5);

        kfc.setReviews("khalid", "bad service", 0);
        kfc.setReviews("mohammad", "great service", 5);
        String expected = "Restaurant{name='kfc', stars=2.5, price='$$$$$', reviews=[khalid, bad service, 0, " +
                "mohammad, great service, 5]}";
        assertEquals(expected, kfc.toString());
    }

    @Test
    void testSetReviewForEachResturent() {
        System.out.println("test 4 SUCCESS");
        Restaurant shawermaji = new Restaurant();
        shawermaji.setName("shawermaji");
        shawermaji.setStars(0);
        shawermaji.setPrice(2);
        Restaurant maker = new Restaurant();
        maker.setName("maker");
        maker.setStars(0);
        maker.setPrice(5);

        shawermaji.setReviews("yaser", "bad service", 0);

        maker.setReviews("khalid", "great service", 5);


        ArrayList<String> expected1 = new ArrayList<String>();
        expected1.add("yaser");
        expected1.add("bad service");
        expected1.add("0");
        assertEquals(expected1, shawermaji.getReviews());
        ArrayList<String> expected2 = new ArrayList<String>();
        expected2.add("khalid");
        expected2.add("great service");
        expected2.add("5");
        assertEquals(expected2, maker.getReviews());
    }

    @Test
    void testUpdateStars() {
        System.out.println("test 5 SUCCESS");
        Restaurant shawermaji = new Restaurant();
        shawermaji.setName("shawermaji");
        shawermaji.setStars(0);
        shawermaji.setPrice(5);

        shawermaji.setReviews("yaser", "bad service", 0);
        shawermaji.setReviews("sameer", "great service", 5);
        shawermaji.setReviews("mohammad", "great service", 1);
        double expected = 2.0;
        assertEquals(expected, shawermaji.getStars());
    }
}
