/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.Arrays;

import static linter.App.errors;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void linterWork() {
        ArrayList<String> recievedArray = errors("./src/main/resources/yaserTest.js");
        ArrayList<String> expectedArray = new ArrayList<String>();
        expectedArray.add("Line 3: Missing semicolon.");
        expectedArray.add("Line 5: Missing semicolon.");
        expectedArray.add("Line 9: Missing semicolon.");

        assertEquals(
                recievedArray, expectedArray);


    }
}
